### ISSUE TITLE
Get Access token for 2 different App

### ISSUE THREAD

**Issue by nadeem4** [manishrasrani/ms-adal-angular6#11]
Hey, 

Can you help me out to get a access token for 2 apps,  one is WebApi and other is native.

Thanks in advance.

**Comment by manishrasrani** [comment]
You can add multiple resources in the endpoint array of adal config and then obtain token for each of them.

**Comment by sonphnt** [comment]
@manishrasrani  Hi, I have the same issue and tried to put resources in endpoint array of adal config but still get the same token no matter what URL in Endpoint.

The property "aud" in token is always Angular ClientID.

Have you made this work with 2 apps solution Angular + WebAPI 

Thanks
