### ISSUE TITLE
[Dependencies] Update Angular Dependencies

### ISSUE THREAD

**Issue by DouglasOGarrido** [manishrasrani/ms-adal-angular6#12]
Hi,

Angular 7 has arrived couple months ago and when I updated my project dependencies, I noticed two warnings from NPM:
"microsoft-adal-angular6@1.0.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself".
"microsoft-adal-angular6@1.0.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself".

I don't know if this impacts your project, but if do, the approach would be update the dependencies or create another repository named "ms-adal-angular7".

If the dependencies not affect this project, forget all that I wrote above :laughing:.

Thks!

**Comment by manishrasrani** [comment]
@DouglasOGarrido - Well I did create a new Angular 7 project and consumed this adal package and verified all scenarios and nothing seems to be breaking.
Unmet peer dependencies is a very common warning thrown by NPM for a bunch of packages as automatic install of peer dependencies was explicitly removed with npm 3, a good thread can be found here - https://stackoverflow.com/questions/35207380/how-to-install-npm-peer-dependencies-automatically

Also creating another repository and publishing another package for Angular7 will not be required as the same package can be used with both Angular 6 and 7, will update the readme to call it out explicitly.
