### ISSUE TITLE
acquireToken service refreshes application

### ISSUE THREAD

**Issue by prashant214** [manishrasrani/ms-adal-angular6#15]
When ever I generate resource level tokens using acquireToken() my application refreshes and takes me to the redirect url.This should not happen as I am already authenticated and now making call to fetch resource level token.
Please suggest how to handle this.

**Comment by muswain** [comment]
I also face the same issue.Whenever either accessToken() or RenewToken() is called, the page gets refreshed completely. Also the expireTimeOffset doesn't seem to work for properly refreshing the token before it expires.
This is the primary requirement to auto renew the idtoken so that it can be used silently in SPAs

**Comment by prashant214** [comment]
@muswain I am trying few workarounds for this in case I will get success will share with you.

**Comment by boxingrex** [comment]
@prashant214 Any luck on a work around? I too am facing this issue.

**Comment by roffus** [comment]
I'm facing the same issue. Any work around?

**Comment by prashant214** [comment]
No Still facing same issue.

**Comment by kkeighran** [comment]
Getting the same behavior.  When token expires, acquireToken will refresh it (although the user is temporarily unauthorized).  Once new token is acquired, the page refreshes after the new token is acquired.  

As a workaround, I tried managing the token expiration myself and calling RenewToken() before the expiration.  That didn't work either.  It actually has the opposite effect.  User is then unauthenticated... (isAuthenticated is false).   So there is a total of 3 issues with keeping the user seamlessly authenticated.

1) Refreshing the app when acquiring new token
2) RenewToken() doesn't work
3) Waiting for actual expiration before renewal

**Comment by prashant214** [comment]
> Getting the same behavior. When token expires, acquireToken will refresh it (although the user is temporarily unauthorized). Once new token is acquired, the page refreshes after the new token is acquired.
> 
> As a workaround, I tried managing the token expiration myself and calling RenewToken() before the expiration. That didn't work either. It actually has the opposite effect. User is then unauthenticated... (isAuthenticated is false). So there is a total of 3 issues with keeping the user seamlessly authenticated.
> 
> 1. Refreshing the app when acquiring new token
> 2. RenewToken() doesn't work
> 3. Waiting for actual expiration before renewal

Hi use expireOffsetSeconds and set it to 600 which means if your token expiration time is 60 minutes it will try to get new token at 50th minute. Also use acquireToken() with your application clientID it will fetch token for you, but make sure you do it before expiry time and expiry time is manage by expireOffsetSeconds . Hope this helps.

**Comment by tarundhillon** [comment]
@prashant214 @manishrasrani 

While the above approach will address the expiry scenario, but in my case I need to acquireToken (s) for external resources which also result into an app refresh in angular for each acquireToken call. 

I have tried couple of workaround options mentioned here https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs without much success. 

Any suggestions or direction will be greatly appreciated. 

Thanks
