### ISSUE TITLE
ID Token Not getting renewed

### ISSUE THREAD

**Issue by prashant214** [manishrasrani/ms-adal-angular6#20]

**Comment by prashant214** [comment]
My ID token is not getting renewed and after 1 hours it expires and my all the api calls are getting failed.
Please suggest how to renew token before it expires.

**Comment by TheAifam5** [comment]
Tried this?

```
interval(5 * 60 * 1000)
      .pipe(
        flatMap(() => this.refreshToken()),
      )
      .subscribe(() => {
        console.log('Refreshing token...');
      });
```

**Comment by prashant214** [comment]
> Tried this?
> 
> ```
> interval(5 * 60 * 1000)
>       .pipe(
>         flatMap(() => this.refreshToken()),
>       )
>       .subscribe(() => {
>         console.log('Refreshing token...');
>       });
> ```

refreshToken is not there.

**Comment by anjum121** [comment]
@prashant214  did you find any solution for this issue?, I am also facing the same.

**Comment by prashant214** [comment]
> @prashant214 did you find any solution for this issue?, I am also facing the same.

Still same for me . You able to find solution for this?

**Comment by prashant214** [comment]
> @prashant214 did you find any solution for this issue?, I am also facing the same.

Use acquireToken(endpoint) and pass your application client in the endpoint. Also make sure you have your  expireOffsetSeconds in the adal config and user is having active session. So if you have token expiry time 1 hour so set expireOffsetSeconds to 600 , it will acquire new token for you after 50 minutes.

**Comment by tecfu** [comment]
Where is expireOffsetSeconds documented? I don't see it here https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#configurable-token-lifetime-properties, nor is it in the README.
