### ISSUE TITLE
Update for Angular 8

### ISSUE THREAD

**Issue by ChristofFritz** [manishrasrani/ms-adal-angular6#22]
Hi, please make it work with Angular8. Currently the Angular CLI prints out the issue 
`Package "microsoft-adal-angular6" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").`
when trying to update the Angular Application to Version 8. 
You can try it out on any Angular 7 project via `ng update @angular/cli @angular/core`

**Comment by micleners** [comment]
@ChristofFritz What worked for me was:
- Uninstall ms-adal-angular6
- Run `ng update`
- Reinstall
- Run the "continue migrate command" it told me to finish the update

I had to uninstall/reinstall again for updating angular material. Looks like our project still works in this end ¯\_(ツ)_/¯

If anyone knows how to loosen the requirement for Angular v6 this would be really helpful! I can't identify where it's coming from.

**Comment by Berezhnyk** [comment]
The name of the library bothers me =) Is it working with Angular 8/9?

**Comment by ChristofFritz** [comment]
I'd suggest to no longer use this library. Just use [msal-angular](https://www.npmjs.com/package/@azure/msal-angular) from Microsoft directly. It has been updated for the current versions of angular and seems like black-magic when compared to this library.
