### ISSUE TITLE
Not able to generate valid token for Microsoft graph API

### ISSUE THREAD

**Issue by nadeem4** [manishrasrani/ms-adal-angular6#3]
var token = this.adalAuth.acquireToken(`https://graph.microsoft.com`)
            .subscribe((token: string) => {
          console.log(token);
          graphAccessToken = token;
        });

**Comment by karthikmcs** [comment]
Same here. In fact, not able generate token for any resource.

**Comment by Oddleif** [comment]
Same here. Able to sign in, get an access token, but when requesting the graph access token it appears to just give back the original access token. In any case, using either I just get access denied when quering the MS Graph.

**Comment by manishrasrani** [comment]
@nadeem4 @karthikmcs @Oddleif - Did you configure the Graph endpoint in the adal configuration? Could you please paste the snippet of the same here?

**Comment by nadeem4** [comment]
![image](https://user-images.githubusercontent.com/30491328/46130506-209e7900-c257-11e8-9b71-c7f0ba1d7a3c.png)

I am also confused about the endpoint.
Can you explain what to put exactly as endpoints?

**Comment by manishrasrani** [comment]
@nadeem4  - You would have to generate a resource level token to access external endpoints.
Please use this for Microsoft Graph API - 
"endPoints": {
"https://graph.microsoft.com": "https://graph.microsoft.com"
}
and then call the this.adalAuth.acquireToken(https://graph.microsoft.com) like you have mentioned above.

**Comment by nadeem4** [comment]
@manishrasrani can I access the user of the azure tenant using this

**Comment by manishrasrani** [comment]
@nadeem4 - depends on the configuration of the tenant. If you are not able to access, please ask the admin of the tenant to provide admin consent to your App Id(Client Id) to access users.
