### ISSUE TITLE
Unable to call graph api using this.adalSvc.accessToken to retrieve user group information

### ISSUE THREAD

**Issue by niravkanakhara** [manishrasrani/ms-adal-angular6#32]
Unable to call graph api using this.adalSvc.accessToken to retrieve user group information

**Comment by niravkanakhara** [comment]
It was my mistake...have to generate new token using aquiretoken..its working now

**Comment by bhanu2507** [comment]
I am still getting below error.
    "code": "InvalidAuthenticationToken",
    "message": "CompactToken parsing failed with error code: 80049217",

Is there any AD side config that is needed.

Thanks
