### ISSUE TITLE
Is there an interceptor in this package?

### ISSUE THREAD

**Issue by PilotBob** [manishrasrani/ms-adal-angular6#4]
I set it up, followed the directions but my Http requests aren't getting a bearer token in the header.

The example only used the Adal6service to get user info. I don't see an example of making an Http request that has the bearer token added to the headers.

thanks.

**Comment by manishrasrani** [comment]
There is no interceptor included as part of this package, you can set up your own interceptor and pass whatever Http headers you require to your service, token can be obtained using - this.adalSvc.acquireToken() method. I will be updating the sample application by adding an interceptor and making a Http call.

**Comment by PilotBob** [comment]
It looks like acquireToken returns an observable? Also, will acquireToken() refresh the token if it is expired?

Thanks.
