### ISSUE TITLE
How to logout or any method for logout

### ISSUE THREAD

**Issue by systenics-ankit** [manishrasrani/ms-adal-angular6#5]

**Comment by Fallenstedt** [comment]
@systenics-ankit When you use this service, there is a public method called logout

https://github.com/manishrasrani/ms-adal-angular6/blob/master/projects/ms-adal-angular6/src/ms-adal-angular6.service.ts#L35-L37

As an example, you can have a button that on click calls `logout`:

```
@Component({
selector: 'foo'
})
export class App Component {

constructor(private adalSvc: MsAdalAngular6Service){}

public logout() {
  this.adalSvc.logout()
}

}
```

**Comment by manishrasrani** [comment]
Agree with @Fallenstedt answer, closing this issue.
