### ISSUE TITLE
Dynamic configuration

### ISSUE THREAD

**Issue by vogloblinsky** [manishrasrani/ms-adal-angular6#7]
Is it possible to set the configuration at runtime ?

We are loading for our project the information for the mas adal module from a json file loaded during initialization of angular, like in this example (juristr.com/blog/2018/01/ng-app-runtime-config/#runtime-configuration)

**Comment by unsafecode** [comment]
This is actually becoming kinda critical, because of https://github.com/angular/angular-cli/issues/10957. In short, AOT build performs some changes in decorator values, and even `window.location.origin` is `null`. So we need a way to lazy-init this module __outside of @NgModule decorators__

**Comment by manishrasrani** [comment]
It is now possible to set the adal config at runtime, changes published in version 1.2.0. Please see the steps mentioned in 'Step 2: Import MsAdalModule and configure Adal options' on how to do it. Thanks to @unsafecode for implementing this feature!
